project: captain-codeman
service: hn
version: alpha
runtime: go
api_version: go1

instance_class: F1

automatic_scaling:
  max_concurrent_requests: 16

handlers:
- url: /service-worker.js
  static_files: static/service-worker.js
  upload: static/service-worker.js
  expiration: "1s"
  http_headers:
    Cache-Control: max-age=0, no-cache, no-store, must-revalidate

- url: /manifest.json
  static_files: static/manifest.json
  upload: static/manifest.json
  expiration: "1s"
  http_headers:
    Cache-Control: max-age=0, no-cache, no-store, must-revalidate

- url: /static/
  static_dir: static
  expiration: "1d"
  http_headers:
    Cache-Control: public, max-age=604800
    Vary: Accept-Encoding
  secure: always

- url: /.*
  script: default/_go_app
  secure: always
  redirect_http_response_code: 301
